demo:
  display-name: demo

weather:
  appid: 8524275445e52a2fbf499dd3182cb9dd

logging:
  level:
    com.example.demo.WeatherFeignClient: DEBUG
spring:
  data:
    mongodb:
      uri: mongodb://admin:admin01@ds143156.mlab.com:43156/demo